export const ROUTES = {
  NEW: "/hang-moi",
  SHIRT: "/ao-nam",
  TROUSER: "/quan-nam",
  ACCESSORY: "/phu-kien",
  SHOE: "/giay-dep",
  SALE: "/giam-gia",
  HOME: "/",
  USER: "/user",

  LOGO: "/",
  SEARCH: "/search",
  CART: "/gio-hang",
  SIGN_UP: "/tao-tai-khoan",
  POLO_SHIRT: "/ao-po-lo",
  DRESS_SHIRT: "/ao-so-mi",
  T_SHIRT: "/ao-thun",
  JACKET_SHIRT: "/ao-khoac",
  SWEATER_SHIRT: "/ao-sweater",
  HOODIE_SHIRT: "/ao-hoodie",
  JEAN_PANT: "/quan-jeans",
  TROUSER_PANT: "/quan-tay",
  KAKI_PANT: "/quan-kaki",
  JOGGER_PANT: "/quan-jogger",
  SORT_PANT: "/quan-sort",
  BELT: "/that-lung",
  WALLET: "/vi-da",
  HAT: "/mu-non",
  BAG: "/tui-xach",
  GLASSES: "/mat-kinh",
  SNEAKER: "/giay-sneaker",
  BOOT: "/giay-boot",
  SANDAL: "/giay-sandal",
  SLIDES: "/dep-nam",
};
